### ISSUE TITLE
How to get sun & moon position at now

### ISSUE THREAD

**Issue by zyo00ody** [waynedgrant/practical-astronomy#1]
Hi @waynedgrant , it looks like your script is amazing ! but I didn't understand it !

First how I can get moon and sun position now (new Date()) and location (lat, lon)?

Second how can I get sun -and moon- rise and set for today or tomorrow?

Thank you

**Comment by waynedgrant** [comment]
Hello @zyo00ody. practical-astronomy was a work in progress where I was working though Peter Duffet-Smith's book from front to back. I had yet to get to the chapters on solar and lunar calcs. I've abandoned work on this js library. I'm instead working on a php version which is port of the VBA functions specific to solar and lunar calculations. This isn't available on github yet.

**Comment by zyo00ody** [comment]
Do you know I'm searching for PHP script for solar and lunar calculations for more than a year, and I didn't find any script except one called SunCalc but it is not accurate at all, and one another have many problems.
I'm waiting you php script !
